# Generated by Django 3.0.5 on 2020-11-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='Course Name')),
                ('course_description', models.CharField(default='Coumputer Course', max_length=300, verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=30, verbose_name='Student Name')),
                ('fat_name', models.CharField(max_length=30, verbose_name='Father Name')),
                ('mat_name', models.CharField(max_length=30, verbose_name='Mother Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('qualification', models.CharField(max_length=20, verbose_name='Qualification')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('caste', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('GM', 'GM')], max_length=10, verbose_name='Csate')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Jain', 'Jain'), ('Christian', 'Christian')], max_length=20, verbose_name='Religion')),
                ('des_time', models.TimeField(verbose_name='Desire Time')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('stud_number', models.CharField(max_length=11, verbose_name="Student's Number")),
                ('pre_number', models.CharField(max_length=11, verbose_name="Perent's Number")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comclass.Course')),
            ],
        ),
    ]
