# Generated by Django 3.0.5 on 2021-03-31 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role_no',
            field=models.CharField(blank=True, default='0', max_length=3, null=True, verbose_name='Student Roll NO'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Student ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_addmission',
            field=models.CharField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2021, max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(max_length=300, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comclass.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Student Name'),
        ),
    ]
